USER-SUPPLIED VALUES:
affinity: {}
airflowConfigAnnotations: {}
airflowHome: /opt/airflow
airflowLocalSettings: |-
  {{- if semverCompare ">=2.2.0" .Values.airflowVersion }}
  {{- if not (or .Values.webserverSecretKey .Values.webserverSecretKeySecretName) }}
  from airflow.www.utils import UIAlert

  DASHBOARD_UIALERTS = [
    UIAlert(
      'Usage of a dynamic webserver secret key detected. We recommend a static webserver secret key instead.'
      ' See the <a href='
      '"https://airflow.apache.org/docs/helm-chart/stable/production-guide.html#webserver-secret-key">'
      'Helm Chart Production Guide</a> for more details.',
      category="warning",
      roles=["Admin"],
      html=True,
    )
  ]
  {{- end }}
  {{- end }}
airflowPodAnnotations: {}
airflowVersion: 2.2.3
allowPodLaunching: true
cleanup:
  affinity: {}
  args:
  - bash
  - -c
  - exec airflow kubernetes cleanup-pods --namespace={{ .Release.Namespace }}
  command: null
  enabled: false
  nodeSelector: {}
  resources: {}
  schedule: '*/15 * * * *'
  securityContext: {}
  serviceAccount:
    annotations: {}
    create: true
    name: null
  tolerations: []
config:
  api:
    auth_backend: airflow.api.auth.backend.deny_all
  celery:
    worker_concurrency: 16
  celery_kubernetes_executor:
    kubernetes_queue: kubernetes
  core:
    colored_console_log: "False"
    dags_folder: '{{ include "airflow_dags" . }}'
    executor: '{{ .Values.executor }}'
    load_examples: "False"
    remote_logging: '{{- ternary "True" "False" .Values.elasticsearch.enabled }}'
  elasticsearch:
    json_format: "True"
    log_id_template: '{dag_id}_{task_id}_{execution_date}_{try_number}'
  elasticsearch_configs:
    max_retries: 3
    retry_timeout: "True"
    timeout: 30
  kerberos:
    ccache: '{{ .Values.kerberos.ccacheMountPath }}/{{ .Values.kerberos.ccacheFileName
      }}'
    keytab: '{{ .Values.kerberos.keytabPath }}'
    principal: '{{ .Values.kerberos.principal }}'
    reinit_frequency: '{{ .Values.kerberos.reinitFrequency }}'
  kubernetes:
    airflow_configmap: '{{ include "airflow_config" . }}'
    airflow_local_settings_configmap: '{{ include "airflow_config" . }}'
    multi_namespace_mode: '{{ if .Values.multiNamespaceMode }}True{{ else }}False{{
      end }}'
    namespace: '{{ .Release.Namespace }}'
    pod_template_file: '{{ include "airflow_pod_template_file" . }}/pod_template_file.yaml'
    worker_container_repository: '{{ .Values.images.airflow.repository | default .Values.defaultAirflowRepository
      }}'
    worker_container_tag: '{{ .Values.images.airflow.tag | default .Values.defaultAirflowTag
      }}'
  logging:
    colored_console_log: "False"
    remote_logging: '{{- ternary "True" "False" .Values.elasticsearch.enabled }}'
  metrics:
    statsd_host: '{{ printf "%s-statsd" .Release.Name }}'
    statsd_on: '{{ ternary "True" "False" .Values.statsd.enabled }}'
    statsd_port: 9125
    statsd_prefix: airflow
  scheduler:
    run_duration: 41460
    statsd_host: '{{ printf "%s-statsd" .Release.Name }}'
    statsd_on: '{{ ternary "True" "False" .Values.statsd.enabled }}'
    statsd_port: 9125
    statsd_prefix: airflow
  webserver:
    enable_proxy_fix: "True"
    rbac: "True"
createUserJob:
  affinity: {}
  annotations: {}
  extraContainers: []
  extraVolumeMounts: []
  extraVolumes: []
  jobAnnotations: {}
  nodeSelector: {}
  resources: {}
  securityContext: {}
  serviceAccount:
    annotations: {}
    create: true
    name: null
  tolerations: []
  useHelmHooks: true
dags:
  gitSync:
    branch: main
    containerName: git-sync
    depth: 1
    enabled: true
    env: []
    extraVolumeMounts: []
    maxFailures: 0
    repo: ssh://git@github.com/jp021996/teste_Stone.git
    resources: {}
    rev: HEAD
    securityContext: {}
    sshKeySecret: airflow-ssh-git-secret
    subPath: /dags
    uid: 65533
    wait: 60
  persistence:
    accessMode: ReadWriteOnce
    enabled: false
    existingClaim: null
    size: 1Gi
    storageClassName: null
data:
  brokerUrl: null
  brokerUrlSecretName: null
  metadataConnection:
    db: postgres
    host: null
    pass: postgres
    port: 5432
    protocol: postgresql
    sslmode: disable
    user: postgres
  metadataSecretName: null
  resultBackendConnection: null
  resultBackendSecretName: null
defaultAirflowRepository: apache/airflow
defaultAirflowTag: 2.2.3
elasticsearch:
  connection: {}
  enabled: false
  secretName: null
enableBuiltInSecretEnvVars:
  AIRFLOW__CELERY__BROKER_URL: true
  AIRFLOW__CELERY__CELERY_RESULT_BACKEND: true
  AIRFLOW__CELERY__RESULT_BACKEND: true
  AIRFLOW__CORE__FERNET_KEY: true
  AIRFLOW__CORE__SQL_ALCHEMY_CONN: true
  AIRFLOW__ELASTICSEARCH__ELASTICSEARCH_HOST: true
  AIRFLOW__ELASTICSEARCH__HOST: true
  AIRFLOW__WEBSERVER__SECRET_KEY: true
  AIRFLOW_CONN_AIRFLOW_DB: true
env: []
executor: CeleryExecutor
extraConfigMaps: {}
extraEnv: null
extraEnvFrom: null
extraSecrets: null
fernetKey: null
fernetKeySecretName: null
flower:
  affinity: {}
  args:
  - bash
  - -c
  - |-
    exec \
    airflow {{ semverCompare ">=2.0.0" .Values.airflowVersion | ternary "celery flower" "flower" }}
  command: null
  enabled: true
  extraContainers: []
  extraNetworkPolicies: []
  extraVolumes: []
  networkPolicy:
    ingress:
      from: []
      ports:
      - port: '{{ .Values.ports.flowerUI }}'
  nodeSelector: {}
  password: null
  podAnnotations: {}
  resources: {}
  secretName: null
  securityContext: {}
  service:
    annotations: {}
    loadBalancerIP: null
    loadBalancerSourceRanges: []
    ports:
    - name: flower-ui
      port: '{{ .Values.ports.flowerUI }}'
    type: ClusterIP
  serviceAccount:
    annotations: {}
    create: true
    name: null
  tolerations: []
  username: null
fullnameOverride: ""
gid: 0
images:
  airflow:
    pullPolicy: IfNotPresent
    repository: null
    tag: null
  flower:
    pullPolicy: IfNotPresent
    repository: null
    tag: null
  gitSync:
    pullPolicy: IfNotPresent
    repository: k8s.gcr.io/git-sync/git-sync
    tag: v3.3.0
  migrationsWaitTimeout: 60
  pgbouncer:
    pullPolicy: IfNotPresent
    repository: apache/airflow
    tag: airflow-pgbouncer-2021.04.28-1.14.0
  pgbouncerExporter:
    pullPolicy: IfNotPresent
    repository: apache/airflow
    tag: airflow-pgbouncer-exporter-2021.09.22-0.12.0
  pod_template:
    pullPolicy: IfNotPresent
    repository: null
    tag: null
  redis:
    pullPolicy: IfNotPresent
    repository: redis
    tag: 6-buster
  statsd:
    pullPolicy: IfNotPresent
    repository: apache/airflow
    tag: airflow-statsd-exporter-2021.04.28-v0.17.0
  useDefaultImageForMigration: false
ingress:
  enabled: false
  flower:
    annotations: {}
    host: ""
    hosts: []
    ingressClassName: ""
    path: /
    pathType: ImplementationSpecific
    tls:
      enabled: false
      secretName: ""
  web:
    annotations: {}
    host: ""
    hosts: []
    ingressClassName: ""
    path: /
    pathType: ImplementationSpecific
    precedingPaths: []
    succeedingPaths: []
    tls:
      enabled: false
      secretName: ""
kerberos:
  ccacheFileName: cache
  ccacheMountPath: /var/kerberos-ccache
  config: |
    # This is an example config showing how you can use templating and how "example" config
    # might look like. It works with the test kerberos server that we are using during integration
    # testing at Apache Airflow (see `scripts/ci/docker-compose/integration-kerberos.yml` but in
    # order to make it production-ready you must replace it with your own configuration that
    # Matches your kerberos deployment. Administrators of your Kerberos instance should
    # provide the right configuration.

    [logging]
    default = "FILE:{{ template "airflow_logs_no_quote" . }}/kerberos_libs.log"
    kdc = "FILE:{{ template "airflow_logs_no_quote" . }}/kerberos_kdc.log"
    admin_server = "FILE:{{ template "airflow_logs_no_quote" . }}/kadmind.log"

    [libdefaults]
    default_realm = FOO.COM
    ticket_lifetime = 10h
    renew_lifetime = 7d
    forwardable = true

    [realms]
    FOO.COM = {
      kdc = kdc-server.foo.com
      admin_server = admin_server.foo.com
    }
  configPath: /etc/krb5.conf
  enabled: false
  keytabBase64Content: null
  keytabPath: /etc/airflow.keytab
  principal: airflow@FOO.COM
  reinitFrequency: 3600
kubeVersionOverride: ""
labels: {}
limits: []
logs:
  persistence:
    enabled: false
    existingClaim: null
    size: 100Gi
    storageClassName: null
migrateDatabaseJob:
  affinity: {}
  annotations: {}
  extraContainers: []
  extraVolumeMounts: []
  extraVolumes: []
  jobAnnotations: {}
  nodeSelector: {}
  resources: {}
  securityContext: {}
  serviceAccount:
    annotations: {}
    create: true
    name: null
  tolerations: []
  useHelmHooks: true
multiNamespaceMode: false
nameOverride: ""
networkPolicies:
  enabled: false
nodeSelector: {}
pgbouncer:
  affinity: {}
  args: null
  ciphers: normal
  command:
  - pgbouncer
  - -u
  - nobody
  - /etc/pgbouncer/pgbouncer.ini
  configSecretName: null
  enabled: false
  extraIni: null
  extraIniMetadata: null
  extraIniResultBackend: null
  extraNetworkPolicies: []
  extraVolumeMounts: []
  extraVolumes: []
  logConnections: 0
  logDisconnections: 0
  maxClientConn: 100
  metadataPoolSize: 10
  metricsExporterSidecar:
    resources: {}
    sslmode: disable
  nodeSelector: {}
  podDisruptionBudget:
    config:
      maxUnavailable: 1
    enabled: false
  resources: {}
  resultBackendPoolSize: 5
  service:
    extraAnnotations: {}
  serviceAccount:
    annotations: {}
    create: true
    name: null
  ssl:
    ca: null
    cert: null
    key: null
  sslmode: prefer
  tolerations: []
  uid: 65534
  verbose: 0
podTemplate: null
ports:
  airflowUI: 8080
  flowerUI: 5555
  pgbouncer: 6543
  pgbouncerScrape: 9127
  redisDB: 6379
  statsdIngest: 9125
  statsdScrape: 9102
  workerLogs: 8793
postgresql:
  enabled: true
  postgresqlPassword: postgres
  postgresqlUsername: postgres
quotas: {}
rbac:
  create: true
  createSCCRoleBinding: false
redis:
  affinity: {}
  enabled: true
  nodeSelector: {}
  password: null
  passwordSecretName: null
  persistence:
    enabled: true
    size: 1Gi
    storageClassName: null
  resources: {}
  safeToEvict: true
  serviceAccount:
    annotations: {}
    create: true
    name: null
  terminationGracePeriodSeconds: 600
  tolerations: []
registry:
  connection: {}
  secretName: null
scheduler:
  affinity: {}
  args:
  - bash
  - -c
  - exec airflow scheduler
  command: null
  extraContainers: []
  extraInitContainers: []
  extraVolumeMounts: []
  extraVolumes: []
  livenessProbe:
    failureThreshold: 5
    initialDelaySeconds: 10
    periodSeconds: 60
    timeoutSeconds: 20
  logGroomerSidecar:
    args:
    - bash
    - /clean-logs
    command: null
    enabled: true
    resources: {}
    retentionDays: 15
  nodeSelector: {}
  podAnnotations: {}
  podDisruptionBudget:
    config:
      maxUnavailable: 1
    enabled: false
  replicas: 1
  resources: {}
  safeToEvict: true
  securityContext: {}
  serviceAccount:
    annotations: {}
    create: true
    name: null
  strategy: null
  tolerations: []
  updateStrategy: null
secret: []
securityContext: {}
statsd:
  affinity: {}
  enabled: true
  extraMappings: []
  extraNetworkPolicies: []
  nodeSelector: {}
  resources: {}
  securityContext: {}
  service:
    extraAnnotations: {}
  serviceAccount:
    annotations: {}
    create: true
    name: null
  tolerations: []
  uid: 65534
tolerations: []
triggerer:
  affinity: {}
  args:
  - bash
  - -c
  - exec airflow triggerer
  command: null
  enabled: true
  extraContainers: []
  extraInitContainers: []
  extraVolumeMounts: []
  extraVolumes: []
  livenessProbe:
    failureThreshold: 5
    initialDelaySeconds: 10
    periodSeconds: 60
    timeoutSeconds: 20
  nodeSelector: {}
  podAnnotations: {}
  replicas: 1
  resources: {}
  safeToEvict: true
  securityContext: {}
  serviceAccount:
    annotations: {}
    create: true
    name: null
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 50%
  terminationGracePeriodSeconds: 60
  tolerations: []
uid: 50000
webserver:
  affinity: {}
  allowPodLogReading: true
  args:
  - bash
  - -c
  - exec airflow webserver
  command: null
  defaultUser:
    email: admin@example.com
    enabled: true
    firstName: admin
    lastName: user
    password: admin
    role: Admin
    username: admin
  extraContainers: []
  extraInitContainers: []
  extraNetworkPolicies: []
  extraVolumeMounts: []
  extraVolumes: []
  livenessProbe:
    failureThreshold: 20
    initialDelaySeconds: 15
    periodSeconds: 5
    timeoutSeconds: 30
  networkPolicy:
    ingress:
      from: []
      ports:
      - port: '{{ .Values.ports.airflowUI }}'
  nodeSelector: {}
  podAnnotations: {}
  readinessProbe:
    failureThreshold: 20
    initialDelaySeconds: 15
    periodSeconds: 5
    timeoutSeconds: 30
  replicas: 1
  resources: {}
  securityContext: {}
  service:
    annotations: {}
    loadBalancerIP: null
    loadBalancerSourceRanges: []
    ports:
    - name: airflow-ui
      port: '{{ .Values.ports.airflowUI }}'
    type: ClusterIP
  serviceAccount:
    annotations: {}
    create: true
    name: null
  strategy: null
  tolerations: []
  webserverConfig: null
webserverSecretKey: null
webserverSecretKeySecretName: null
workers:
  affinity: {}
  args:
  - bash
  - -c
  - |-
    exec \
    airflow {{ semverCompare ">=2.0.0" .Values.airflowVersion | ternary "celery worker" "worker" }}
  command: null
  extraContainers: []
  extraInitContainers: []
  extraVolumeMounts: []
  extraVolumes: []
  hostAliases: []
  keda:
    cooldownPeriod: 30
    enabled: false
    maxReplicaCount: 10
    minReplicaCount: 0
    namespaceLabels: {}
    pollingInterval: 5
  kerberosSidecar:
    enabled: false
    resources: {}
  logGroomerSidecar:
    args:
    - bash
    - /clean-logs
    command: null
    resources: {}
    retentionDays: 15
  nodeSelector: {}
  persistence:
    enabled: true
    fixPermissions: false
    size: 100Gi
    storageClassName: null
  podAnnotations: {}
  replicas: 1
  resources: {}
  safeToEvict: true
  securityContext: {}
  serviceAccount:
    annotations: {}
    create: true
    name: null
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 50%
  terminationGracePeriodSeconds: 600
  tolerations: []
  updateStrategy: null
